# name 可以自定义
name: Deploy GitHub Pages

# 触发条件：在 push 到 main/master 分支后，新的 Github 项目 应该都是 main，而之前的项目一般都是 master
on:
  push:
    branches:
      - main

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # "最近更新时间"等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
        #使用action安装node环境
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 生成静态文件
      - name: Build
        run: cat /home/runner/work/ckhr516.github.io/ckhr516.github.io/docs/随笔/7.新建测试.md && npm install && npm run build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: my-blog # 部署到的分支
          folder: docs/.vuepress/dist # vuepress 生成的静态文件存放的地方
